### ISSUE TITLE
Custom colours for notifications badges

### ISSUE THREAD

**Issue by Heroslfb** [ClearVision/Addons#2]
Hey. really nice theme and addons. Thanks for it.

I find it inconvenient that "--main-color" is used as a color for in app noti badges 
![изображение](https://user-images.githubusercontent.com/109235048/178977487-cde01773-3b2d-4ef3-b68a-e2d00791fbd3.png)
Is it possible to set up color and may be text color for this badges in "ClearVision_v6.theme.css" file please?

Also it would be nice to have an option to setup transparency and overlay color for background of messages where I was tagged. Sometimes it's hard to find out I was tagged at first glance. Original ds theme deal great with this
![изображение](https://user-images.githubusercontent.com/109235048/178978321-e39d9130-1a4f-46d3-bb3a-d27ae8dacce1.png)

Thanks

**Comment by NyxIsBad** [comment]
Open a ticket in the cv discord if you're still interested in this topic, I know I'm getting to you like half a year too late, sorry!
